# Generated by Django 3.0.1 on 2020-01-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_remove_photo_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
