# Generated by Django 3.0.1 on 2020-01-12 22:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 12, 22, 18, 58, 723841, tzinfo=utc)),
        ),
    ]
