# Generated by Django 3.0.1 on 2020-01-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_photo_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='pub_date',
        ),
    ]
