# Generated by Django 3.0.1 on 2020-01-12 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_photo_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 12, 22, 34, 35, 268995, tzinfo=utc)),
        ),
    ]
