# Generated by Django 3.0.1 on 2020-01-13 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20200113_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contact name', max_length=100)),
                ('role', models.CharField(choices=[('Head Instructor', 'Head Instructor'), ('Instructor', 'Instructor'), ('Assistant Instructor', 'Assistant Instructor')], max_length=50)),
                ('phone_number', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('email_address', models.EmailField(help_text='Contact email address', max_length=254)),
                ('image', models.ImageField(upload_to='contact_images')),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 13, 16, 47, 45, 428170, tzinfo=utc)),
        ),
    ]
