# Generated by Django 3.0.1 on 2020-01-13 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20200113_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=14),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 13, 17, 7, 51, 388290, tzinfo=utc)),
        ),
    ]
