# Generated by Django 3.0.1 on 2020-01-13 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_auto_20200113_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 13, 17, 8, 53, 620710, tzinfo=utc)),
        ),
    ]
